[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "monitor-tmrs"
version = "0.21.1b1"
description = "Dashboard para acompanhamento da Taxa de Manejo de Resíduos Sólidos, conforme a Lei n. 1.218/2026."
requires-python = ">=3.10"
dependencies = [
    "requests",
    "pandas",
    "lxml",
]

[project.optional-dependencies]
dev = [
    "mypy",
    "types-requests",
    "pandas-stubs",
]

[tool.setuptools.packages.find]
include = ["jobs*"]
